baseURL: https://r4modellers.netlify.app/
languageCode: en-us
title: R for Environmental Modellers
theme: hugo-theme-cactus
copyright: Gayan Gunaratne
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: yes
    style: dracula
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    enabled: yes
    engine: disqus
  dateFormat: '2006-01-02'
  description: Hugo is a general-purpose website framework. Technically speaking,
    Hugo is a static site generator. Unlike systems that dynamically build a page
    with each visitor request, Hugo builds pages when you create or update your content.
    Since websites are viewed far more often than they are edited, Hugo is designed
    to provide an optimal viewing experience for your website’s end users and an ideal
    writing experience for website authors.
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gohugoio
  rss: yes
  show_updated: yes
  showAllPostsArchive: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  showReadTime: yes
  social:
    - link: https://github.com/gayandream
      name: github
    - link: https://www.linkedin.com/in/gayan-gunaratne-45313219/?originalSubdomain=au
      name: linkedin
    - link: gayandream@yahoo.com
      name: email
  tagsOverview: yes
