baseURL: https://r4modellers.netlify.app/
languageCode: en-us
title: R for Environmental Modellers
theme: hugo-theme-cactus
copyright: Gayan Gunaratne
disqusShortname: example
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: Posts
      url: /posts
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name: About
      url: /about
      weight: 4
markup:
  highlight:
    codeFences: yes
    guessSyntax: no
    hl_Lines: ''
    lineNoStart: 1
    lineNos: yes
    lineNumbersInTable: no
    noClasses: yes
    style: dracula
    tabWidth: 4
  tableOfContents:
    endLevel: 4
    ordered: no
    startLevel: 2
params:
  colortheme: white
  comments:
    enabled: yes
    engine: disqus
  dateFormat: '2006-01-02'
  description: If you use R for environmental modelling you might find something helpful here. 
    If you dont know who is an environmental modeller, probably google search is the best option.
    I sometimes write R scripts, because it make my work life easier.
    R scripts facilitate automation across my modelling decslplnes including hydrodynamic and water quality modelling. 
    You will find a few blog posts here about my R scripts and their usage.
    I am wrting this blog for me. Thus, under no circumstances I'm under any obligation to make sense any blog posts to you.
    However, your consctructive crticism is always accepted and appreciated.
    Because I wanna get beetr at what I'm doing (what ever this is ).
  googleAnalyticsAsync: yes
  mainSection: posts
  postsOnHomePage: 5
  projectsUrl: https://github.com/gayandream
  rss: yes
  show_updated: yes
  showAllPostsArchive: no
  showAllPostsOnHomePage: no
  showProjectsList: yes
  showReadTime: yes
  social:
    - link: https://github.com/gayandream
      name: github
    - link: https://www.linkedin.com/in/gayan-gunaratne-45313219/?originalSubdomain=au
      name: linkedin
    - link: gayandream@yahoo.com
      name: email
  tagsOverview: yes
