---
title: "Creating an irregular interval time series"
author: "Gayan Gnaratne"
date: "Last compiled on `r format(Sys.time(), '%d %B, %Y')`"
#date: 14-09-2021
output: 
  bookdown::html_document2:
  #html_document:
  toc: true
  toc_float: true
  number_sections: true
theme: united
  
---

```{r lib, message = FALSE, warnings = FALSE, comment=FALSE, results=FALSE}
#libraries
library(here)
library (dplyr)
library(tidyr)
library(ggplot2)
```

## Creating irregular time series by setting up start and end date times.

```{r define_date_times}
start_date<- "2021-04-01"
end_date<- "2021-05-31"

my_date_format<- "%Y-%m-%d %H:%M"
time_interval <- "1440 min"

time1 <- "00:01"
end_time <- "23:59"
time2 <- "06:59"
time3 <- "07:00"
time4 <- "10:00"
time5 <- "10:01"
time6 <- "14:59"
time7 <- "15:00"
time8 <- "18:00"
time9 <- "18:01"

feed_release <- 0.002536783
faecal1_release <- 0.031075596
faecal2_release <- 0.039827499
faecal3_release <- 0.05339929


start_time1<-as.POSIXct(paste(start_date, time1),format=my_date_format)
end_time1<-as.POSIXct(paste(end_date, end_time),format=my_date_format)
start_time2<-as.POSIXct(paste(start_date, time2),format=my_date_format)
end_time2<-as.POSIXct(paste(end_date, time2),format=my_date_format)
start_time3<-as.POSIXct(paste(start_date, time3),format=my_date_format)
end_time3<-as.POSIXct(paste(end_date, time3),format=my_date_format)
start_time4<-as.POSIXct(paste(start_date, time4),format=my_date_format)
end_time4<-as.POSIXct(paste(end_date, time4),format=my_date_format)
start_time5<-as.POSIXct(paste(start_date, time5),format=my_date_format)
end_time5<-as.POSIXct(paste(end_date, time5),format=my_date_format)
start_time6<-as.POSIXct(paste(start_date, time6),format=my_date_format)
end_time6<-as.POSIXct(paste(end_date, time6),format=my_date_format)
start_time7<-as.POSIXct(paste(start_date, time7),format=my_date_format)
end_time7<-as.POSIXct(paste(end_date, time7),format=my_date_format)
start_time8<-as.POSIXct(paste(start_date, time8),format=my_date_format)
end_time8<-as.POSIXct(paste(end_date, time8),format=my_date_format)
start_time9<-as.POSIXct(paste(start_date, time9),format=my_date_format)
end_time9<-as.POSIXct(paste(end_date, time9),format=my_date_format)

```




```{r time_series}
df1<-setNames(data.frame(seq(from=start_time1,to=end_time1,by=time_interval,format=my_date_format)),"time")
df2<-setNames(data.frame(seq(from=start_time2,to=end_time2,by=time_interval,format=my_date_format)),"time")
df3<-setNames(data.frame(seq(from=start_time3,to=end_time3,by=time_interval,format=my_date_format)),"time")
df4<-setNames(data.frame(seq(from=start_time4,to=end_time4,by=time_interval,format=my_date_format)),"time")
df5<-setNames(data.frame(seq(from=start_time5,to=end_time5,by=time_interval,format=my_date_format)),"time")
df6<-setNames(data.frame(seq(from=start_time6,to=end_time6,by=time_interval,format=my_date_format)),"time")
df7<-setNames(data.frame(seq(from=start_time7,to=end_time7,by=time_interval,format=my_date_format)),"time")
df8<-setNames(data.frame(seq(from=start_time8,to=end_time8,by=time_interval,format=my_date_format)),"time")
df9<-setNames(data.frame(seq(from=start_time9,to=end_time9,by=time_interval,format=my_date_format)),"time")

time_series<-Reduce(function(x,y) merge(x,y,by="time",all=TRUE) ,list(df1,df2,df3,df4,df5,df6,df7,df8,df9))
head(time_series)
```


```{r add_feed}

time_series$date_time <- format(as.POSIXct(time_series$time), "%d-%m-%Y %H:%M")
#head(time_series)

time_series1 <- separate(data = time_series, col = date_time, into  = c('Date', 'Time'), sep = ' ')
head(time_series1)

# for feed
time_series1<-time_series1 %>%
     mutate(feed = case_when((Time == time3) ~ feed_release,
                              (Time == time4) ~ feed_release,
                              (Time == time7) ~ feed_release,
                              (Time == time8) ~ feed_release,
                            TRUE ~ 0))

# for fecal1
time_series1<-time_series1 %>%
     mutate(faecal_1= case_when((Time == time3) ~ faecal1_release,
                              (Time == time4) ~ faecal1_release,
                              (Time == time7) ~ faecal1_release,
                              (Time == time8) ~ faecal1_release,
                            TRUE ~ 0))
# for fecal2
time_series1<-time_series1 %>%
     mutate(faecal_2= case_when((Time == time3) ~ faecal2_release,
                              (Time == time4) ~ faecal2_release,
                              (Time == time7) ~ faecal2_release,
                              (Time == time8) ~ faecal2_release,
                            TRUE ~ 0))

# for fecal3
time_series1<-time_series1 %>%
     mutate(faecal_3= case_when((Time == time3) ~ faecal3_release,
                              (Time == time4) ~ faecal3_release,
                              (Time == time7) ~ faecal3_release,
                              (Time == time8) ~ faecal3_release,
                            TRUE ~ 0))
head(time_series1)

```



```{r wrte_to_csv}

time_series1 <-time_series1 %>%
  unite("Date_time", Date:Time,na.rm = TRUE, remove = TRUE,sep=' ')
head(time_series1)
time_series2<-time_series1 %>%
  mutate(TIME = gsub('-', '/', Date_time))%>%
  select(TIME,feed,faecal_1,faecal_2,faecal_3)


head(time_series2)

write.csv(time_series2, file="particle_release_time_series.csv",row.names = FALSE,quote=F)

```
```{r plot}
time_series3 <-time_series1 [,c(1,3:6)]
time_series3 <-time_series3 %>%
  pivot_longer(-time,names_to = "particle_name",values_to = "value")
head(time_series3)

#plot
p <- ggplot(time_series3, aes(x=time, y=value,group=particle_name, colour=particle_name)) +
  geom_point() + 
  xlab("")
p
```

